import { Layout } from "@/components/Layout";
import { getPostsMetaData } from "@/lib/getPostsData";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home({ navigation }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="grid gap-6 py-8">
          {navigation.map((post, index) => (
            <div className="grid grid-cols-2 gap-4 flex-1" key={index}>
              <Image
                src={"http://placehold.it/600x400"}
                alt=""
                width="600"
                height="400"
              />
              <div className="flex items-center">
                <div>
                  <Link href={`/posts/${post.slug}`}>
                    <h2 className="font-bold text-2xl mb-2">{post.title}</h2>
                    <button className="px-4 py-2 bg-black text-white rounded-md">
                      Read more
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const navigation = getPostsMetaData();
  return {
    props: {
      navigation,
    },
  };
}
